name: CI

on: pull_request

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1.1.0
        with:
          terraform_version: 0.12.28

      - name: Terraform format
        run: terraform fmt -check -recursive .
